# Start MPV centered
geometry=50%:50%

# Never allow the window to open larger than 90% of your screen
autofit-larger=90%x90%

# Ensure it doesn't open too tiny for low-res videos
autofit-smaller=30%x30%
