-- Cyberpunk Neon Theme for Neovim
-- Tailored to Kitty & Hyprland config with transparent background
-- Inherits background from Kitty (#090a0f @ 0.65 opacity + blur) just like btop and htop

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "cyberpunk"
vim.o.termguicolors = true

local c = {
  bg = "NONE",
  bg_dark = "#090a0f",
  bg_card = "#12141d",
  bg_highlight = "#1c1e26",
  bg_visual = "#ff00aa",
  fg = "#00ffcc",
  fg_bright = "#ffffff",
  fg_dim = "#7fe8d5",
  cyan = "#00ffcc",
  pink = "#ff00aa",
  magenta = "#ff00aa",
  yellow = "#fcee0a",
  blue = "#00aaff",
  green = "#00ff99",
  red = "#ff0055",
  gray = "#4e5569",
  dark_gray = "#282c3f",
  comment = "#536878",
  purple_glow = "#2d133b",
  none = "NONE",
}

local hl = {
  -- Base Editor
  Normal = { fg = c.fg, bg = c.none },
  NormalNC = { fg = c.fg_dim, bg = c.none },
  NormalFloat = { fg = c.fg, bg = c.none },
  FloatBorder = { fg = c.cyan, bg = c.none },
  FloatTitle = { fg = c.pink, bg = c.none, bold = true },
  SignColumn = { fg = c.cyan, bg = c.none },
  FoldColumn = { fg = c.gray, bg = c.none },
  LineNr = { fg = c.gray, bg = c.none },
  LineNrAbove = { fg = c.dark_gray, bg = c.none },
  LineNrBelow = { fg = c.dark_gray, bg = c.none },
  CursorLineNr = { fg = c.pink, bg = c.none, bold = true },
  CursorLine = { bg = "#10121a" },
  CursorColumn = { bg = "#10121a" },
  EndOfBuffer = { fg = c.bg_highlight, bg = c.none },
  VertSplit = { fg = c.pink, bg = c.none },
  WinSeparator = { fg = c.pink, bg = c.none, bold = true },
  ColorColumn = { bg = "#141724" },
  Conceal = { fg = c.comment, bg = c.none },

  -- Cursor & Selection (Identical to Kitty)
  Cursor = { fg = c.bg_dark, bg = c.pink },
  lCursor = { fg = c.bg_dark, bg = c.cyan },
  CursorIM = { fg = c.bg_dark, bg = c.yellow },
  TermCursor = { fg = c.bg_dark, bg = c.pink },
  TermCursorNC = { fg = c.bg_dark, bg = c.gray },
  Visual = { fg = c.fg_bright, bg = c.pink, bold = true },
  VisualNOS = { fg = c.fg_bright, bg = c.pink },

  -- Search & Matching
  Search = { fg = c.bg_dark, bg = c.yellow, bold = true },
  IncSearch = { fg = c.bg_dark, bg = c.pink, bold = true },
  CurSearch = { fg = c.bg_dark, bg = c.pink, bold = true },
  MatchParen = { fg = c.yellow, bg = c.none, bold = true, underline = true },

  -- Status & Tabline
  StatusLine = { fg = c.cyan, bg = c.none },
  StatusLineNC = { fg = c.gray, bg = c.none },
  TabLine = { fg = c.gray, bg = c.none },
  TabLineFill = { bg = c.none },
  TabLineSel = { fg = c.pink, bg = c.none, bold = true },
  WinBar = { fg = c.cyan, bg = c.none, bold = true },
  WinBarNC = { fg = c.gray, bg = c.none },

  -- Popup Menus (Pmenu)
  Pmenu = { fg = c.cyan, bg = c.bg_dark },
  PmenuSel = { fg = c.fg_bright, bg = c.pink, bold = true },
  PmenuSbar = { bg = c.bg_card },
  PmenuThumb = { bg = c.cyan },
  WildMenu = { fg = c.bg_dark, bg = c.yellow, bold = true },

  -- Messages & Prompts
  ModeMsg = { fg = c.yellow, bold = true },
  MoreMsg = { fg = c.green, bold = true },
  Question = { fg = c.cyan, bold = true },
  Title = { fg = c.pink, bold = true },
  WarningMsg = { fg = c.yellow, bold = true },
  ErrorMsg = { fg = c.red, bold = true },

  -- Standard Syntax Highlighting
  Comment = { fg = c.comment, italic = true },
  Constant = { fg = c.red },
  String = { fg = c.green },
  Character = { fg = c.green },
  Number = { fg = c.red, bold = true },
  Boolean = { fg = c.red, bold = true },
  Float = { fg = c.red, bold = true },
  Identifier = { fg = c.cyan },
  Function = { fg = c.yellow, bold = true },
  Statement = { fg = c.pink, bold = true },
  Conditional = { fg = c.pink, bold = true },
  Repeat = { fg = c.pink, bold = true },
  Label = { fg = c.yellow },
  Operator = { fg = c.pink },
  Keyword = { fg = c.pink, bold = true },
  Exception = { fg = c.red, bold = true },
  PreProc = { fg = c.blue },
  Include = { fg = c.blue, bold = true },
  Define = { fg = c.blue },
  Macro = { fg = c.blue },
  PreCondit = { fg = c.blue },
  Type = { fg = c.blue, bold = true },
  StorageClass = { fg = c.blue },
  Structure = { fg = c.blue, bold = true },
  Typedef = { fg = c.blue },
  Special = { fg = c.yellow },
  SpecialChar = { fg = c.yellow },
  Tag = { fg = c.pink },
  Delimiter = { fg = c.cyan },
  SpecialComment = { fg = c.yellow, italic = true },
  Debug = { fg = c.red },
  Underlined = { fg = c.cyan, underline = true },
  Ignore = { fg = c.gray },
  Error = { fg = c.fg_bright, bg = c.red, bold = true },
  Todo = { fg = c.bg_dark, bg = c.yellow, bold = true },

  -- Treesitter Highlights
  ["@variable"] = { fg = c.cyan },
  ["@variable.builtin"] = { fg = c.red, italic = true },
  ["@variable.parameter"] = { fg = c.fg_dim, italic = true },
  ["@variable.member"] = { fg = c.cyan },
  ["@constant"] = { fg = c.red },
  ["@constant.builtin"] = { fg = c.red, bold = true },
  ["@constant.macro"] = { fg = c.blue },
  ["@string"] = { fg = c.green },
  ["@string.regex"] = { fg = c.yellow },
  ["@string.escape"] = { fg = c.yellow, bold = true },
  ["@character"] = { fg = c.green },
  ["@number"] = { fg = c.red },
  ["@boolean"] = { fg = c.red, bold = true },
  ["@number.float"] = { fg = c.red },
  ["@annotation"] = { fg = c.yellow },
  ["@attribute"] = { fg = c.yellow },
  ["@module"] = { fg = c.blue },
  ["@module.builtin"] = { fg = c.blue, bold = true },
  ["@function"] = { fg = c.yellow, bold = true },
  ["@function.builtin"] = { fg = c.yellow, bold = true },
  ["@function.macro"] = { fg = c.blue },
  ["@function.method"] = { fg = c.yellow, bold = true },
  ["@function.call"] = { fg = c.yellow },
  ["@function.method.call"] = { fg = c.yellow },
  ["@constructor"] = { fg = c.blue, bold = true },
  ["@keyword"] = { fg = c.pink, bold = true },
  ["@keyword.function"] = { fg = c.pink, bold = true },
  ["@keyword.return"] = { fg = c.pink, bold = true },
  ["@keyword.operator"] = { fg = c.pink },
  ["@keyword.conditional"] = { fg = c.pink, bold = true },
  ["@keyword.repeat"] = { fg = c.pink, bold = true },
  ["@keyword.import"] = { fg = c.blue, bold = true },
  ["@keyword.exception"] = { fg = c.red, bold = true },
  ["@operator"] = { fg = c.pink },
  ["@type"] = { fg = c.blue, bold = true },
  ["@type.builtin"] = { fg = c.blue },
  ["@type.definition"] = { fg = c.blue, bold = true },
  ["@type.qualifier"] = { fg = c.pink },
  ["@property"] = { fg = c.cyan },
  ["@punctuation.delimiter"] = { fg = c.cyan },
  ["@punctuation.bracket"] = { fg = c.cyan },
  ["@punctuation.special"] = { fg = c.pink },
  ["@comment"] = { fg = c.comment, italic = true },
  ["@comment.documentation"] = { fg = c.comment, italic = true },
  ["@comment.error"] = { fg = c.red, bold = true },
  ["@comment.warning"] = { fg = c.yellow, bold = true },
  ["@comment.todo"] = { fg = c.bg_dark, bg = c.yellow, bold = true },
  ["@tag"] = { fg = c.pink, bold = true },
  ["@tag.attribute"] = { fg = c.yellow },
  ["@tag.delimiter"] = { fg = c.cyan },

  -- Diagnostics
  DiagnosticError = { fg = c.red },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticInfo = { fg = c.cyan },
  DiagnosticHint = { fg = c.green },
  DiagnosticVirtualTextError = { fg = c.red, bg = c.none, italic = true },
  DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.none, italic = true },
  DiagnosticVirtualTextInfo = { fg = c.cyan, bg = c.none, italic = true },
  DiagnosticVirtualTextHint = { fg = c.green, bg = c.none, italic = true },
  DiagnosticUnderlineError = { undercurl = true, sp = c.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = c.cyan },
  DiagnosticUnderlineHint = { undercurl = true, sp = c.green },

  -- LSP semantic tokens
  ["@lsp.type.class"] = { fg = c.blue, bold = true },
  ["@lsp.type.decorator"] = { fg = c.yellow },
  ["@lsp.type.enum"] = { fg = c.blue, bold = true },
  ["@lsp.type.enumMember"] = { fg = c.red },
  ["@lsp.type.function"] = { fg = c.yellow, bold = true },
  ["@lsp.type.interface"] = { fg = c.blue, bold = true },
  ["@lsp.type.macro"] = { fg = c.blue },
  ["@lsp.type.method"] = { fg = c.yellow, bold = true },
  ["@lsp.type.namespace"] = { fg = c.blue },
  ["@lsp.type.parameter"] = { fg = c.fg_dim, italic = true },
  ["@lsp.type.property"] = { fg = c.cyan },
  ["@lsp.type.struct"] = { fg = c.blue, bold = true },
  ["@lsp.type.type"] = { fg = c.blue, bold = true },
  ["@lsp.type.variable"] = { fg = c.cyan },

  -- Git / Diff
  DiffAdd = { fg = c.green, bg = c.none },
  DiffChange = { fg = c.blue, bg = c.none },
  DiffDelete = { fg = c.red, bg = c.none },
  DiffText = { fg = c.yellow, bg = c.none, bold = true },
  GitSignsAdd = { fg = c.green, bg = c.none },
  GitSignsChange = { fg = c.blue, bg = c.none },
  GitSignsDelete = { fg = c.red, bg = c.none },

  -- Telescope
  TelescopeNormal = { fg = c.cyan, bg = c.none },
  TelescopeBorder = { fg = c.cyan, bg = c.none },
  TelescopeTitle = { fg = c.pink, bg = c.none, bold = true },
  TelescopePromptNormal = { fg = c.fg_bright, bg = c.none },
  TelescopePromptBorder = { fg = c.pink, bg = c.none },
  TelescopePromptTitle = { fg = c.bg_dark, bg = c.pink, bold = true },
  TelescopePromptPrefix = { fg = c.pink, bold = true },
  TelescopePreviewTitle = { fg = c.bg_dark, bg = c.yellow, bold = true },
  TelescopePreviewBorder = { fg = c.yellow, bg = c.none },
  TelescopePreviewNormal = { fg = c.cyan, bg = c.none },
  TelescopeResultsTitle = { fg = c.bg_dark, bg = c.cyan, bold = true },
  TelescopeResultsBorder = { fg = c.cyan, bg = c.none },
  TelescopeResultsNormal = { fg = c.cyan, bg = c.none },
  TelescopeSelection = { fg = c.fg_bright, bg = c.purple_glow, bold = true },
  TelescopeSelectionCaret = { fg = c.pink, bold = true },
  TelescopeMatching = { fg = c.yellow, bold = true },

  -- NvimTree
  NvimTreeNormal = { fg = c.cyan, bg = c.none },
  NvimTreeNormalNC = { fg = c.cyan, bg = c.none },
  NvimTreeEndOfBuffer = { fg = c.none, bg = c.none },
  NvimTreeWinSeparator = { fg = c.pink, bg = c.none },
  NvimTreeFolderName = { fg = c.blue, bold = true },
  NvimTreeFolderIcon = { fg = c.blue },
  NvimTreeOpenedFolderName = { fg = c.pink, bold = true },
  NvimTreeRootFolder = { fg = c.yellow, bold = true },
  NvimTreeGitDirty = { fg = c.yellow },
  NvimTreeGitNew = { fg = c.green },
  NvimTreeGitDeleted = { fg = c.red },
  NvimTreeSpecialFile = { fg = c.yellow, bold = true },
  NvimTreeExecFile = { fg = c.green, bold = true },
  NvimTreeImageFile = { fg = c.pink },
  NvimTreeIndentMarker = { fg = c.dark_gray },

  -- Bufferline
  BufferLineFill = { bg = c.none },
  BufferLineBackground = { fg = c.gray, bg = c.none },
  BufferLineBufferSelected = { fg = c.cyan, bg = c.none, bold = true },
  BufferLineIndicatorSelected = { fg = c.pink, bg = c.none },
  BufferLineModified = { fg = c.yellow, bg = c.none },
  BufferLineModifiedSelected = { fg = c.yellow, bg = c.none },
  BufferLineSeparator = { fg = c.bg_highlight, bg = c.none },
  BufferLineSeparatorSelected = { fg = c.pink, bg = c.none },
  BufferLineTab = { fg = c.gray, bg = c.none },
  BufferLineTabSelected = { fg = c.pink, bg = c.none, bold = true },

  -- WhichKey
  WhichKey = { fg = c.pink, bold = true },
  WhichKeyGroup = { fg = c.blue },
  WhichKeyDesc = { fg = c.cyan },
  WhichKeyFloat = { bg = c.none },
  WhichKeyBorder = { fg = c.cyan, bg = c.none },
  WhichKeyValue = { fg = c.yellow },
  WhichKeySeparator = { fg = c.gray },

  -- Indent Blankline
  IblIndent = { fg = c.bg_highlight },
  IblWhitespace = { fg = c.bg_highlight },
  IblScope = { fg = c.pink },

  -- Alpha Dashboard
  AlphaHeader = { fg = c.pink, bold = true },
  AlphaButtons = { fg = c.cyan },
  AlphaShortcut = { fg = c.yellow, bold = true },
  AlphaFooter = { fg = c.gray, italic = true },

  -- CMP (Completion)
  CmpItemAbbr = { fg = c.cyan },
  CmpItemAbbrDeprecated = { fg = c.gray, strikethrough = true },
  CmpItemAbbrMatch = { fg = c.yellow, bold = true },
  CmpItemAbbrMatchFuzzy = { fg = c.yellow, bold = true },
  CmpItemKind = { fg = c.pink },
  CmpItemMenu = { fg = c.comment, italic = true },
  CmpItemKindFunction = { fg = c.yellow },
  CmpItemKindMethod = { fg = c.yellow },
  CmpItemKindVariable = { fg = c.cyan },
  CmpItemKindKeyword = { fg = c.pink },
  CmpItemKindText = { fg = c.fg_dim },
  CmpItemKindClass = { fg = c.blue },
  CmpItemKindInterface = { fg = c.blue },
  CmpItemKindSnippet = { fg = c.green },
}

for group, opts in pairs(hl) do
  vim.api.nvim_set_hl(0, group, opts)
end
