color_theme = "TTY"
truecolor = true
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "threads"
show_cpu_watts = true
show_battery = true
show_battery_watts = true
