# Fonts
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

# Window layout
window_padding_width 12
hide_window_decorations yes
confirm_os_window_close 0

# Cyberpunk Colors
background #090a0f
foreground #00ffcc
selection_background #ff00aa
selection_foreground #ffffff

# Cursor
cursor #ff00aa
cursor_text_color #ffffff
cursor_shape block
cursor_blink_interval 0.5

# Transparency (Looks great with Hyprland Blur)
background_opacity 0.65
dynamic_background_opacity yes

# ANSI Colors (Neon Palette)
# Black
color0  #090a0f
color8  #1c1e26
# Red
color1  #ff0055
color9  #ff0055
# Green
color2  #00ff99
color10 #00ff99
# Yellow
color3  #fcee0a
color11 #fcee0a
# Blue
color4  #00aaff
color12 #00aaff
# Magenta
color5  #ff00aa
color13 #ff00aa
# Cyan
color6  #00ffcc
color14 #00ffcc
# White
color7  #e0e0e0
color15 #ffffff
